# Generated by Django 2.2 on 2020-03-23 06:11

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Location', 'verbose_name_plural': 'Locations'},
        ),
        migrations.AlterField(
            model_name='location',
            name='points',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, verbose_name='points'),
        ),
    ]
