# Generated by Django 2.2 on 2020-03-10 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relation',
            options={'verbose_name': 'Relation', 'verbose_name_plural': 'Relations'},
        ),
    ]
