# Generated by Django 2.2 on 2020-03-30 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_auto_20200323_0611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_time',
            field=models.DateField(auto_now=True, verbose_name='created_time'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='modified_time',
            field=models.DateField(auto_now_add=True, verbose_name='modified_time'),
        ),
        migrations.AlterField(
            model_name='like',
            name='created_time',
            field=models.DateField(auto_now=True, verbose_name='created_time'),
        ),
        migrations.AlterField(
            model_name='like',
            name='modified_time',
            field=models.DateField(auto_now_add=True, verbose_name='modified_time'),
        ),
    ]
