# Generated by Django 2.2 on 2020-04-02 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200305_1052'),
        ('user', '0003_auto_20200320_1525'),
    ]

    operations = [
    ]
