# Generated by Django 2.2 on 2020-05-01 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200319_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='followers_count',
        ),
        migrations.RemoveField(
            model_name='user',
            name='following_count',
        ),
    ]
