# Generated by Django 2.2 on 2020-03-10 06:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.AlterModelOptions(
            name='postmedia',
            options={'verbose_name': 'PostMedia', 'verbose_name_plural': 'PostsMedia'},
        ),
        migrations.AlterModelOptions(
            name='posttag',
            options={'verbose_name': 'PostTag', 'verbose_name_plural': 'PostsTags'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.AlterModelOptions(
            name='taggeduser',
            options={'verbose_name': 'TaggedUser', 'verbose_name_plural': 'TaggedUsers'},
        ),
        migrations.AlterField(
            model_name='postmedia',
            name='media_file',
            field=models.FileField(upload_to='content/media/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('jpg', 'jpeg', 'mp4', 'wmv', 'flv', 'png'))], verbose_name='media file'),
        ),
    ]
