# Generated by Django 2.2 on 2020-03-23 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20200323_0554'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.AlterModelOptions(
            name='postmedia',
            options={'verbose_name': 'PostMedia', 'verbose_name_plural': 'PostMedias'},
        ),
        migrations.AlterModelOptions(
            name='posttag',
            options={'verbose_name': 'PostTag', 'verbose_name_plural': 'PostTags'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.AlterModelOptions(
            name='tagegeduser',
            options={'verbose_name': 'TaggedUser', 'verbose_name_plural': 'TaggedUsers'},
        ),
    ]
