# Generated by Django 2.2 on 2020-04-02 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20200310_0619'),
        ('content', '0004_auto_20200330_0425'),
    ]

    operations = [
    ]
